# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Motivation'
  link: '/motivation'
- label: 'Kickstart'
  link: '/kickstart'
- label: 'Purpose of Computer'
  link: '/purpose-of-computer'
- label: 'Purpose of Programming'
  link: '/purpose-of-programming'
- label: 'Why Do We Learn Programming?'
  link: '/why-do-we-learn-programming'
- label: 'Pseudo Code'
  link: '/pseudo-code'
- label: 'Programming Fundamentals'
  items:
      - label: 'Overview'
        link: '/programming-fundamentals/overview'
      - label: 'Variables'
        link: '/programming-fundamentals/variables'
      - label: 'Operators'
        link: '/programming-fundamentals/operators'
      - label: 'Conditions'
        link: '/programming-fundamentals/conditions'
