# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Motivation'
  link: '/motivation'
- label: 'Kickstart'
  link: '/kickstart'
- label: 'Purpose of Computer'
  link: '/purpose_of_computer'
- label: 'Purpose of Programming'
  link: '/purpose_of_programming'
- label: 'Why Do We Learn Programming?'
  link: '/why_do_we_learn_programming'
- label: 'Pseudo Code'
  link: '/pseudo_code'
