# Sidebar navigation

- label: 'Welcome'
  link: '/'
- label: 'Motivation'
  link: '/motivation'
- label: 'Kickstart'
  link: '/kickstart'
- label: 'Purpose of Computer'
  link: '/purpose-of-computer'
- label: 'Purpose of Programming'
  link: '/purpose-of-programming'
- label: 'Why Do We Learn Programming?'
  link: '/why-do-we-learn-programming'
- label: 'Pseudo Code'
  link: '/pseudo-code'
- label: 'Programming Fundamentals'
  items:
      - label: 'Overview'
        link: '/programming-fundamentals/overview'
      - label: 'Variables'
        link: '/programming-fundamentals/variables'
      - label: 'Operators'
        link: '/programming-fundamentals/operators'
      - label: 'Conditions'
        link: '/programming-fundamentals/conditions'
- label: 'Stack Learner'
  items:
      - label: 'Free Courses'
        link: 'https://youtube.com/stacklearner'
      - label: 'Premium Courses'
        link: 'https://courses.stackschool.co'
      - label: 'Stack Journal'
        link: 'https://journal.stacklearner.com'
      - label: 'Official Page'
        link: 'https://facebook.com/stacklearner'
      - label: 'Programming Group'
        link: 'https://facebook.com/groups/stacklearner'
      - label: 'Linkedin Page'
        link: 'https://www.linkedin.com/company/stacklearner'
      - label: 'Official Instagram'
        link: 'https://instagram.com/stacklearner'
      - label: 'Medium Publication'
        link: 'https://medium.com/stack-learner'
